server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      __path__: /var/log/nginx/*log
  - targets:
      - localhost
    labels:
      job: grafana
      __path__: /var/log/grafana/*log 
  - targets:
      - localhost
    labels:
      job: dpkg-logs
      __path__: /var/log/dpkg.log
  - targets:
      - localhost
    labels:
      job: syslog
      __path__: /var/log/syslog

